# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/my-ml-library',
                'doc_host': 'https://terencemichale.github.io',
                'git_url': 'https://github.com/terencemichale/my-ml-library',
                'lib_path': 'my_ml_library'},
  'syms': {'my_ml_library.core': {'my_ml_library.core.foo': ('core.html#foo', 'my_ml_library/core.py')}}}
